### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by THuffam** [AIWintermuteAI/aXeleRate#13]
Hi
Just tried a fresh install on a new VM (Ubuntu Desktop 16.04.6 64-bit), followed instructions but when I tried running tests_training.py I get the following error:
ModuleNotFoundError: No module named 'tensorflow.keras.layers.experimental.preprocessing'
...
ImportError: Keras requires Tensorflow 2.2 or higher.

Obviously a dependency issue...just not sure which has the wrong version... TF or Keras??

Any suggestions? 
Thanks
Tim

**Comment by AIWintermuteAI** [comment]
Hello!
How are you installing aXeleRate? From `pip install aXeleRate` or `pip install git+https://github.com/AIWintermuteAI/aXeleRate` ?
Either way it is really strange... I cannot find any code containing tensorflow.keras.layers.experimental.preprocessing --- and I don't remember adding it, because I am yet to update aXeleRate to tf.keras.
![Screenshot from 2020-06-24 12-01-16](https://user-images.githubusercontent.com/32562299/85498708-c9d3f800-b612-11ea-9908-2abf50c1de3c.png)

**Comment by THuffam** [comment]
Hi 
I did the following:
`pip install git+https://github.com/AIWintermuteAI/aXeleRate`
Followed by:
`git clone https://github.com/AIWintermuteAI/aXeleRate.git`
Then
`python tests_training.com`

Yeah it had me confused too as it is a new, clean environment.

Cheers
Tim

**Comment by THuffam** [comment]
Just checked the versions that the pip install installed:

- keras: 2.4.2
- tensorflow: 1.15.3

I noticed an error when I try to update keras (InvalidArchiveError("Error with archive /home/.... Message from libarchive was: Failed to crate dir 'lib/python3.7/site-packages/tensorflow/python/profiler"   So I deleted that conda env and created a new one.
This time it used keras 2.4.3 and TF 1.15.3

Same error when trying to run tests_training.com.

Then I tried  `conda install "keras<=2.3.2"` - (which seemed to do nothing more than update tensorflow-base-2.2.0) but when I do `conda list` I still see keras: 2.4.3 (very strange)

I tried running tests_training.py again.. and it got a bit further, got error: 
```
python tests_training.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "tests_training.py", line 2, in <module>
    from axelerate import setup_training, setup_inference
  File "/home/tim/Dev/ML/aXeleRate/axelerate/__init__.py", line 1, in <module>
    from .train import setup_training
  File "/home/tim/Dev/ML/aXeleRate/axelerate/train.py", line 19, in <module>
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.5)
AttributeError: module 'tensorflow' has no attribute 'GPUOptions'
```
Any suggestions?
Any idea what is different between your environment and mine?   I specifically created this new environment so I could use the same as you.

Thanks again
Tim.

**Comment by AIWintermuteAI** [comment]
The issue was in Keras package update. I was under the impression that 2.3.1 is going to be last standalone keras version. But tuned out that I was wrong and 2.4.0 was released a few days ago, which is only compatible with tf 2.0. 
I changed the requirements for keras from keras >= 2.3.1 to keras == 2.3.1 in this commit 
https://github.com/AIWintermuteAI/aXeleRate/commit/947eef377394b11df0424ab5a60b1eeb2a067c7b
Please try creating a fresh environment and installing again - btw if you use GPU it is better to install tensorflow-gpu package from conda, it will automatically install cuda/cudnn as well if you haven't done that already. 
Anyways, check the latest commit and see if it resolves the problem :)

**Comment by THuffam** [comment]
Thanks for this.
Just recreated my conda environment.  keras now with 2.3.1 and TF 1.15.3.
Now get the following:
```
python tests_training.py
Using TensorFlow backend.
Project folder /home/ubuntu/space safety/classifier is created.
Traceback (most recent call last):
  File "tests_training.py", line 125, in <module>
    model_path = setup_training(config_dict=item)
  File "/home/tim/Dev/ML/aXeleRate/axelerate/train.py", line 161, in setup_training
    os.makedirs(dirname)
  File "/home/tim/miniconda3/envs/ml/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/tim/miniconda3/envs/ml/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/tim/miniconda3/envs/ml/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu'
```

Where does /home/ubuntu come from?  
Thanks again
Tim

**Comment by AIWintermuteAI** [comment]
From the config dictionary inside tests_training.py
            "saved_folder":   		"/home/ubuntu/space safety/classifier",
https://github.com/AIWintermuteAI/aXeleRate/blob/947eef377394b11df0424ab5a60b1eeb2a067c7b/tests_training.py#L41
https://github.com/AIWintermuteAI/aXeleRate/blob/947eef377394b11df0424ab5a60b1eeb2a067c7b/tests_training.py#L78
https://github.com/AIWintermuteAI/aXeleRate/blob/947eef377394b11df0424ab5a60b1eeb2a067c7b/tests_training.py#L110
I'll correct that in the next release, thank you for noticing this nonsense :)
Just correct them to something like "results/name-for-project-folder" for now.

**Comment by AIWintermuteAI** [comment]
My pleasure!
