### ISSUE TITLE
Tiny yolo

### ISSUE THREAD

**Issue by anhnguyen2345** [AIWintermuteAI/aXeleRate#23]
**Is your feature request related to a problem? Please describe.**
Can I use tiny yolo for training model, tinyyolo and mobilenet what is better ?

If i use architecture is "tiny yolo", what parameter I need to change ?
Thanks.

**Comment by AIWintermuteAI** [comment]
Yes, you can use Tiny TOLO feature extractor. It depends on your application, if you only have small-ish dataset(hundreds of pictures), then I would recommend using MobileNet with imagenet weights, because Tiny YOLO doesn't have pre-trained weights, therefore training will start from scratch.

Feature extractor can be changed with
https://github.com/AIWintermuteAI/aXeleRate/blob/7cec5e510b422c8f63ca29e31c92569e365ce6e4/configs/raccoon_detector.json#L4

Possible options are 
Full Yolo, Tiny Yolo, MobileNet1_0, MobileNet7_5, MobileNet5_0, MobileNet2_5, SqueezeNet, NASNetMobile, ResNet50 or DenseNet121
