### ISSUE TITLE
When class names more than one, the mAP is false?

### ISSUE THREAD

**Issue by wwzh2015** [AIWintermuteAI/aXeleRate#58]
When just have one class the mAp calculate is true, what's happened?

https://ftp.bmp.ovh/imgs/2021/07/9a67e2599fcda7c9.png

Multi classes the mAp is very low.

**Comment by AIWintermuteAI** [comment]
Hi, there.
I don't want to guess what exactly do you mean, could you please describe your issue according to the template here:
https://github.com/AIWintermuteAI/aXeleRate/issues/20
Otherwise, the issue will be marked Closed.

**Comment by wwzh2015** [comment]
> Hi, there.
> I don't want to guess what exactly do you mean, could you please describe your issue according to the template here:
> #20
> Otherwise, the issue will be marked Closed.

the multi labels mAp calculate is not exactly

**Comment by AIWintermuteAI** [comment]
![image](https://user-images.githubusercontent.com/32562299/126461676-79b7903b-6746-4599-9e0c-cfa1b6ceb211.png)

**Comment by wwzh2015** [comment]
Why the multi labels mAp is so  low? but single label mAp is high.

**Comment by AIWintermuteAI** [comment]
Describe the bug
Users are not using template, which causes a waste of time - additional information is needed to be asked by contributors to find the source of the problem.

To Reproduce
Steps to reproduce the behavior:

    Go to 'Issues'
    Click on 'closed'
    Scroll down to 'everywhere'
    See all issues without templates - people are creating issues and asking "what is wrong, it doesn't work" without explaining what is the bug and what is expected behavior

Expected behavior
A clear and concise description of what you expected to happen when you run the code, what is your dataset, what is the error output in the terminal. Ideally, create a colab notebook to reproduce the error and share it here.

Screenshots
If applicable, add screenshots to help explain your problem.

Environment (please complete the following information):

    Local or Google Colab/Jupyter Notebook
    If Local: conda or native install/ virtual env?
    If Google Colab: tensorflow version?

Additional context
Add any other context about the problem here.
