### ISSUE TITLE
How calculate anchors by kmeans? 

### ISSUE THREAD

**Issue by wwzh2015** [AIWintermuteAI/aXeleRate#59]
it will support mobilenet7_5

**Comment by AIWintermuteAI** [comment]
Describe the bug
Users are not using template, which causes a waste of time - additional information is needed to be asked by contributors to find the source of the problem.

To Reproduce
Steps to reproduce the behavior:

    Go to 'Issues'
    Click on 'closed'
    Scroll down to 'everywhere'
    See all issues without templates - people are creating issues and asking "what is wrong, it doesn't work" without explaining what is the bug and what is expected behavior

Expected behavior
A clear and concise description of what you expected to happen when you run the code, what is your dataset, what is the error output in the terminal. Ideally, create a colab notebook to reproduce the error and share it here.

Screenshots
If applicable, add screenshots to help explain your problem.

Environment (please complete the following information):

    Local or Google Colab/Jupyter Notebook
    If Local: conda or native install/ virtual env?
    If Google Colab: tensorflow version?

Additional context
Add any other context about the problem here.

**Comment by wwzh2015** [comment]
I just want take calculate anchors script!
